version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
        - run:
            name:  Running tests 
            command: 
                    docker build -t oviney/ubuntu-intellij .

